---
- hosts: all
  tasks:
        - name: Update the System
          yum:
            name: '*'
            state: latest

        - name: Creating a repository file for Docker
          file:
            path: /etc/yum.repos.d/docker-ce.repo
            state: touch

        - name: Adding repository details in docker-ce.repo file.
          blockinfile:
            path: /etc/yum.repos.d/docker-ce.repo
            block: |
                [docker-ce-stable]
                name=Docker CE Stable - $basearch
                baseurl=https://download.docker.com/linux/centos/7/$basearch/stable
                enabled=1
                gpgcheck=1
                gpgkey=https://download.docker.com/linux/centos/gpg

        - name: yum-makecache
          command: yum makecache -y
          args:
            warn: no

        - name: install container.io
          command: yum install -y https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
          args:
            warn: no

        - name: Install docker-ce
          yum:
            name: docker-ce
            state: latest

        - name: enable docker service
          service:
            name: docker
            enabled: true
            state: started

        - name: add the user to docker group
          user:
            name: sysadmin
            group: docker

        - name: Install required system packages
          yum: name={{ item }} state=latest
          loop: [ 'python38-pip', 'python38-setuptools']

        - name: Install Docker Module for Python
          pip:
            name: docker

        - name: Creating a repository file for Kubernetes
          file:
            path: /etc/yum.repos.d/kubernetes.repo
            state: touch
        - name: Adding repository details in kubernetes repo file.
          blockinfile:
            path: /etc/yum.repos.d/kubernetes.repo
            block: |
                [kubernetes]
                name=Kubernetes
                baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
                enabled=1
                gpgcheck=1
                repo_gpgcheck=1
                gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

        - name: yum-makecache
          command: yum makecache -y
          args:
            warn: no

        - name: Disabling Swap on all nodes
          command: swapoff -a

        - name: Commenting Swap entries in /etc/fstab
          replace:
            path: /etc/fstab
            regexp: '(.*swap*)'
            replace: '#\1'

        - name: Install required system packages
          yum: name={{ item }}
          loop: [ 'kubeadm', 'kubectl', 'kubelet']

        - name: Create k8s.conf file
          file:
            path: /etc/sysctl.d/k8s.conf
            state: touch

        - name: Configure IP Tables
          blockinfile:
            path: /etc/sysctl.d/k8s.conf
            block: |
                net.bridge.bridge-nf-call-ip6tables = 1
                net.bridge.bridge-nf-call-iptables = 1

        - name: Disable firewalld
          service:
            name: firewalld
            enabled: false
            state: stopped

        - name: Disable selinux
          shell: |
           sed -i s/^SELINUX=.*$/SELINUX=permissive/ /etc/selinux/config
           setenforce=0
          args:
            warn: no

        - name: enable kubelet
          service:
                name: kubelet
                enabled: true
                state: started

- hosts: masters
  tasks:
        - name: Pulling images required for setting up a Kubernetes cluster
          shell: kubeadm config images pull

        - name: Initializing Kubernetes cluster
          shell: kubeadm init

        - name: Copying required files
          shell: |
           mkdir -p $HOME/.kube
           cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
           chown $(id -u):$(id -g) $HOME/.kube/config
          args:
            warn: no

        - name: Generate join command
          shell: kubeadm token create --print-join-command
          register: join_command

        - name: Copy join command to local file
          local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

        - name: Install Network Add-on
          command: kubectl apply -f https://cloud.weave.works/k8s/net

- hosts: nodes
  tasks:
        - name: Copy the join command to server location
          copy: src=join-command dest=/tmp/join-command.sh mode=0777

        - name: Join the node to cluster
          shell: sh /tmp/join-command.sh

- hosts: masters
  tasks:
        - name: sleep three minutes till the network plugin be installed correctly
          pause:
                minutes: 3
        - name: install git
          yum:
                name: git
                state: latest
        - name: clone yml files
          git:
                repo: 'https://github.com/AymanZahran/Kubernetes'
                dest: /home/sysadmin/Kubernetes
                clone: yes
                update: no
        - name: deploy kubernetes
          command: kubectl apply -f /home/sysadmin/Kubernetes/deployment.yml
